
# === Orchestrator Config ===

paths:
  lora_folder: "F:/03_Gen AI tools/webui_forge_cu121_torch231/webui/models/Lora"
  model_folder: "F:/03_Gen AI tools/webui_forge_cu121_torch231/webui/models/Stable-diffusion"
  wildcard_folder: "F:/03_Gen AI tools/webui_forge_cu121_torch231/webui/extensions/sd-dynamic-prompts/wildcards"

defaults:
  gpt_enabled: true
  batch_size: 5
  model: "Flux1DevHyperNF4"
  sampler: "Euler"
  steps: 10
  cfg_scale: 3.5
  hires_fix: true
  denoising_strength: 0.4
  hr_scale: 1.43
  upscaler: "4x-AnimeSharp"

theme_presets_file: "./themes/presets.json"
